=== samkit5495/Engineering-Practicals/BE/Sem II/SL-VI/Assignment 7/Others/order/schema.xsd
<?xml version="1.0" encoding="UTF-8"?>

<!-- New XSD document created with EditiX XML Editor (http://www.editix.com) at Thu Jan 12 11:26:23 IST 2017 -->

<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

<xs:element name="Customer">
<xs:complexType>
<xs:sequence>
<xs:element ref="orders" minOccurs="1" maxOccurs="unbounded"></xs:element>
</xs:sequence>
</xs:complexType>
</xs:element>

<xs:element name="orders">
<xs:complexType>
<xs:sequence>
<xs:element ref="custid" minOccurs="0" maxOccurs="1"></xs:element>
<xs:element ref="custname" minOccurs="0" maxOccurs="1"></xs:element>
<xs:element ref="itemname" minOccurs="0" maxOccurs="1"></xs:element>
<xs:element ref="amount" minOccurs="0" maxOccurs="1"></xs:element>
</xs:sequence>
</xs:complexType>
</xs:element>

<xs:element name="custid" type="xs:string"></xs:element>
<xs:element name="custname" type="xs:string"></xs:element>
<xs:element name="itemname" type="xs:string"></xs:element>
<xs:element name="amount" type="xs:integer"></xs:element>

</xs:schema>

=== samkit5495/Engineering-Practicals/BE/Sem II/SL-VI/Assignment 7/Others/order/customerOrders.xml
<?xml version="1.0" encoding="UTF-8"?>

<!-- New XML document created with EditiX XML Editor (http://www.editix.com) at Thu Jan 12 11:35:57 IST 2017 -->


<Customer xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="D:/Dropbox/Documents/College Programs/SL-VI/Assignment 7/order/schema.xsd">


<orders>

	<custid>c101</custid>

	<custname>Samkit</custname>

	<itemname>TV</itemname>

	<amount>10000</amount>

</orders>


<orders>

	<custid>c102</custid>

	<custname>Aish</custname>

	<itemname>Fridge</itemname>

	<amount>25000</amount>

</orders>



<orders>

	<custid>c103</custid>

	<custname>Prachin</custname>

	<itemname>Laptop</itemname>

	<amount>50000</amount>

</orders>


</Customer>
