=== samkit5495/Engineering-Practicals/BE/Sem II/SL-VI/Assignment 7/schema.xsd
<?xml version="1.0" encoding="UTF-8"?>

<!-- New XSD document created with EditiX XML Editor (http://www.editix.com) at Sun Apr 23 13:07:04 IST 2017 -->

<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

<xs:element name="BEIT">
<xs:complexType>
<xs:sequence>
<xs:element ref="Student" minOccurs="0" maxOccurs="unbounded"></xs:element>
</xs:sequence>
</xs:complexType>
</xs:element>

<xs:element name="Student">
<xs:complexType>
<xs:sequence>
	<xs:element ref="first_name" minOccurs="0" maxOccurs="1"></xs:element>
	<xs:element ref="last_name" maxOccurs="1" minOccurs="0"></xs:element>
	<xs:element ref="nick_name" minOccurs="0" maxOccurs="1"></xs:element>
	<xs:element ref="marks" minOccurs="0" maxOccurs="1"></xs:element>
</xs:sequence>
</xs:complexType>
</xs:element>


<xs:element name="first_name" type="xs:string"></xs:element>

<xs:element name="last_name" type="xs:string"></xs:element>
<xs:element name="nick_name" type="xs:string"></xs:element>
<xs:element name="marks" type="xs:float"></xs:element>

</xs:schema>

=== samkit5495/Engineering-Practicals/BE/Sem II/SL-VI/Assignment 7/data.xml
<?xml version="1.0" encoding="UTF-8"?>

<!-- New XML document created with EditiX XML Editor (http://www.editix.com) at Sun Apr 23 13:11:42 IST 2017 -->


<BEIT xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="schema.xsd">

<Student>
<first_name>Samkit</first_name>
<last_name>Jain</last_name>
<nick_name>Sam</nick_name>
<marks>100</marks>
</Student>

<Student>
<first_name>Aishwarya</first_name>
<last_name>Jagtap</last_name>
<nick_name>Aish</nick_name>
<marks>99</marks>
</Student>

<Student>
<first_name>Prachin</first_name>
<last_name>Ranawat</last_name>
<nick_name>Chin</nick_name>
<marks>98</marks>
</Student>

<Student>
<first_name>Prateek</first_name>
<last_name>Sakaray</last_name>
<nick_name>teek</nick_name>
<marks>97</marks>
</Student>

</BEIT>
